# Generated by Django 5.0.6 on 2024-05-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('idade', models.IntegerField()),
                ('cpf', models.IntegerField()),
                ('caminhoImagem', models.TextField(max_length=500)),
            ],
        ),
    ]
